language: generic
os: linux
dist: trusty
sudo: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:samuel-bachmann/boost'
    packages: &base_packages
      - libsqlite3-dev
      - libbotan1.10-dev
      - libz-dev
      - bzip2
      - gcovr
      - cppcheck
      - doxygen
      - lcov
      - libboost-date-time1.60-dev
      - libboost-locale1.60-dev
      - pkg-config
      - libusb-1.0-0-dev
      - libbz2-dev
      - libgnutls-dev
      - libcurl4-gnutls-dev
      - gettext

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-4.9
      env:
        - CXX=g++-4.9

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-5
      env:
        - CXX=g++-5

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-6
      env:
        - CXX=g++-6

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-6
      env:
        - CXX=g++-6
        - CXXSTD=14

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-7
      env:
        - CXX=g++-7

#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - sourceline: 'ppa:samuel-bachmann/boost'
#            - ubuntu-toolchain-r-test
#          packages:
#            - *base_packages
#            - g++-7
#      env:
#        - CXX=g++-7
#        - CXXSTD=17 # Requires cmake 3.9

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
          packages:
            - *base_packages
            - clang++-3.5
      env:
        - CXX=clang++-3.5

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
          packages:
            - *base_packages
            - clang++-3.6
      env:
        - CXX=clang++-3.6

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
          packages:
            - *base_packages
            - clang++-3.8
      env:
        - CXX=clang++-3.8

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
          packages:
            - *base_packages
            - clang++-3.9
      env:
        - CXX=clang++-3.9

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - *base_packages
            - clang++-4.0
      env:
        - CXX=clang++-4.0

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - *base_packages
            - clang++-5.0
      env:
        - CXX=clang++-5.0

# On Travis, this uses libstdc++4.8 and the build fails.
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - sourceline: 'ppa:samuel-bachmann/boost'
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-5.0
#          packages:
#            - *base_packages
#            - clang++-5.0
#      env:
#        - CXX=clang++-5.0
#        - CXXSTD=14

# Doesn't have thread_local.
#    - os: osx
#      osx_image: xcode6.4
#      compiler: clang
#      env:
#       - CXX=clang++

# Doesn't have thread_local.
#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - CXX=clang++

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - CXX=clang++

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env:
        - CXX=clang++

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-7
      env:
        - CXX=g++-7
        - NEOPG_BUILD_TYPE=Debug
      script:
        - $CXX --version
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=${NEOPG_BUILD_TYPE:-Release} -DCOVERAGE=ON ..
        - make -j3 coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-format-4.0
      env:
        - PRETTY=true
      install:
      script:
        - git ls-files -- '*.cpp' '*.h' | grep -v ^3rdparty | xargs clang-format-4.0 -i -style=file
        - git diff --exit-code --color

#  allow_failures:
#    - env:
#        - PRETTY=true
#  fast_finish: true

install:
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew update
      # MacOS comes with libcurl.
      brew install botan doxygen gettext lcov gcovr libusb gnutls
      brew link --force gettext
      # Already installed: cmake boost
    else
      git clone https://github.com/randombit/botan.git
      (cd botan;
      git checkout 2.3.0;
      ./configure.py --with-bzip2 --with-zlib --with-sqlite3;
      sudo make install;
      sudo ldconfig)
    fi

script:
  - $CXX --version
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${NEOPG_BUILD_TYPE:-Release} ..
  - make -j3
  - make test CTEST_OUTPUT_ON_FAILURE=1
